__author__ = 'Huangcius-HL'

guizeyinqing_page_url = 'https://rule.aeptest.ctwing.cn/index.html?token=cbc41f4e-d4b6-4a67-950-050a1eb44b4&true#/rule?t=10070570&token=cbc41f4e-d4b6-4a67-9a50-050a1eb44a'
username_inputbox_xpath = 'xpath->//*[@id="fm1"]/div[1]/div/div[1]/input'
username_inputcontent = 'guoxiaofeng'
password_inputbox_xpath = 'xpath->//*[@id="fm1"]/div[2]/div/div[1]/input'
password_inputcontent = 'Guo521521???'
login_button_xpath = 'xpath->//*[@id="fm1"]/div[4]/div/div[1]/button'
createguize_button_xpath = 'xpath->/html/body/div/div/div/section/main/div[1]/div/div[8]/button'
zhijiecreate_button_xpath = 'xpath->/html/body/div[1]/div/div/section/main/div[2]/div/div[3]/div/div[3]/span/button[1]'
guizemiaoshu_inputbox_xpath = 'xpath->/html/body/div[1]/div/div/section/main/div[2]/div/section/div/div/div[2]/form/div[1]/div/div[1]/input'
guizemiaoshu_inputcontent = 'test'
chanpinxuanze_button_xpath = 'xpath->//*[@id="select-append"]/button[1]'
duiyingchanpin_button_xpath = 'xpath->/html/body/div[3]/div/div[2]/div[1]/div[3]/table/tbody/tr[1]/td[2]'
queding_button_xpath = 'xpath->/html/body/div[3]/div/div[3]/div/button[2]'
guizeneirong_inputbox_xpath = 'xpath->/html/body/div[1]/div/div/section/main/div[2]/div/section/div/div/div[2]/form/div[4]/div/div[2]/div/div/div[2]/textarea'
guizeneirong_inputcontent = 'select'
queding_button_xpath1 = 'xpath->/html/body/div[1]/div/div/section/main/div[2]/div/section/div/div/div[2]/div[2]/div/button[2]'